[0m16:13:17.249298 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1047b7b90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10451a330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104808200>]}


============================== 16:13:17.251576 | 6e09b802-6c9a-4bce-ae67-0da99224a1cf ==============================
[0m16:13:17.251576 [info ] [MainThread]: Running with dbt=1.9.2
[0m16:13:17.251831 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/williampetrosino/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m16:13:17.252055 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/williampetrosino/Git/DataCamp/analytics_engineer/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:13:17.253107 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.045782834, "process_in_blocks": "0", "process_kernel_time": 0.096317, "process_mem_max_rss": "94568448", "process_out_blocks": "0", "process_user_time": 0.462736}
[0m16:13:17.253333 [debug] [MainThread]: Command `dbt run` failed at 16:13:17.253295 after 0.05 seconds
[0m16:13:17.253474 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104792300>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104236720>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1047b5760>]}
[0m16:13:17.253599 [debug] [MainThread]: Flushing usage events
[0m16:13:17.407775 [debug] [MainThread]: An error was encountered while trying to flush usage events
